splashes = {
	"Also try <A game you like>!",
	"Also try <A game you hate>!",
	"Also try <A game you've never heard of>!",
	function() return "the "..string.char(math.random(97,122)) end,
	"#c06000fard",
	"top ten epic cellular machinery",
	"HOW",
	"really reminds you of simpler times",
	"Bringing you twelve hundred cells since 2023!",
	"This is no B-Side!",
	"#80c0ffmovers#ffff00 be like \"i'm push you\"",
	"#ff80ffpullers#ffff00 be like \"come with me\"",
	"#c0ffc0grabbers#ffff00 be like \"i have two arms and i might as well use them\"",
	"#ffc0c0drillers#ffff00 be like \"screw divergers\"",
	"#ff40c0slicers#ffff00 be like \"get out of my way\"",
	"#ffffffnudgers#ffff00 be like \"what is my purpose\"",
	"#c0ff80builders#ffff00 be like \"im gonna crash the game\"",
	function() return math.random(10).."/10" end,
	"blendi goose when strong enemy isn't named double enemy:",
	"Sticky Cell included!",
	"Not a religion!",
	"what's a circle",
	"what's a triangle",
	"what's a hexagon",
	"Bringing you the weirdest cell names you've ever seen!",
	"Omnipower: \"i used to rule the world\"",
	"strong enemy doesn't lift",
	"bulk enemy vs yo mama",
	"is this minecraft",
	"Too many mods!",
	"Not enough mods!",
	"Too many APIs!",
	"Not enough APIs!",
	"Too many printers!",
	"Really, there's a lot.",
	"Where's the bees?",
	"shut fowo",
	"kyyay is sans confirmed!/1?!",
	"Line\nbreaks\nwork!",
	"Are the enemies sentient?",
	"How ethical is enemy genocide?",
	"What if the enemies are the good guys?",
	"What if you were a mover and your only purpose was to move into an enemy cell",
	"lol",
	"leak cellua",
	"love3d when",
	"the c bug isn't real, it can't hurt you",
	"if there are \"inner thoughts\", what the hell is an \"outer thought\"?",
	"cel macin",
	"sell machines",
	"Omnicell has 104976 different combinations for sides!",
	"#ff8080F#ffff80A#80ff80N#8080ffC#ff80ffY",
	"#R\\o1 #mF#MA#rN#RC#rI#ME#mR #R\\o1",
	"hilarious",
	"The slipperiest slope!",
	"Cry about it!",
	"Ultimate sandbox! *\n#606000* opinions may vary from person to person",
	"one of the games of all time",
	"trell",
	"its a sandbox",
	function() local s = ""; for i=1,100 do s = s..string.char(math.random(97,122)) end; return s end,
	"cells are 56 mm^3",
	function() return "The chance of you getting this splash is 1/"..#splashes.."!" end,
	"invisible paint is a horrible idea",
	"dont break the great border it keeps \\o6 out",
	"56 is a magic number in CelLua lore",
	"No#ff8000 crustaceans#ffff00 found...",
	"#rgamer RGB text!!?1?!",
	"HE#f0f010LP,#e0e020 HE#d0d030LP,#c0c040 I'M B#b0b050EING#a0a060 DESA#909070TURA#808080TED!",
	"Touch Grass BG",
	"Cellular!",
	"Automata!",
	"Zero player, except for when it's not!",
	"And KyYay said: Let there be cells.\nAnd there were cells.",
	"Cellmao Machine",
	"It has a few cells.",
	"yeah, i maybe added a couple of cells",
	"\\iItalic!",
	"Where did you come from, where did you go?",
	"Movers move!",
	"More than cells!",
	"Infinite puzzles!",
	"Infinite machines!",
	"Infinite devices!",
	"Infinite potential!",
	"Big!",
	function() local s = ""; for i=1,math.random(1,10) do s = s..(math.random() < .5 and "?" or "!") end; return s end,
	"Roblox is "..string.rep("\\#",7),
	"Spikes are pointy!",
	"Chainsaws are painful!",
	"Icicles are dangerous!",
	"Observers... they watch.",
	"Don't play while driving!",
	"In case you didn't know,#00ff00 Generators#ffff00 are not #0080ffMovers#ffff00.",
	"My cell count is rising... IT'S OVERFLOWING...!",
	"Freshly-baked cells!",
	"Good luck ever finding a new cell idea!",
	"Cells of an uncommon size!",
	"<b><i>i dont think this is working guys</i></b>",
	"This text is yellow!",
	function()
		local r,g,b = math.random(0,255),math.random(0,255),math.random(0,255)
		r,g,b = string.format("%02x",r),string.format("%02x",g),string.format("%02x",b)
		return "#"..r..g..b.."This text is \\#"..r..g..b.."!"
	end,
	"Cells are infinite with CelLua Enterprises.",
	"Pop culture reference here.",
	"while true do end",
	"Made with moon dust!",
	"Baked in the moonlight!",
	"The cells aren't edible, actually.",
	"A bit much?",
	"Puzzling... no, wait, that's another remake.",
	function() return splashsequences[math.random(#splashsequences)] end,
	"add tough twist fast acidic broken squish friendly physical time super con-xnbut bendrowbacktrigate cell",
	"\\o3 \\o4 \\o4 \\o2",	--"you cant read me"
	"#202020I'm stealthy!",
	"kyay",
	"bendi",
	"k",
	"monior",
	"hi :)",
	"Cambrian explosion!",
	"#r_ffffffI like this feature. :)",
	"I'm not sorry.",
	"The Super Enemies, they aren't what you think they are!",
	"Not about biology!",
	"Something is in your logo.",
}

splashsequences = {
	"1, 1, 2, 3, 5, 8, 13, 21, 34, 55...",
	"2, 3, 5, 7, 11, 13, 17, 19, 23, 29...",
	"0, 1, 3, 6, 2, 7, 13, 20, 12, 21...",
	"1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862, 16796...",
	"0, 0, 1, 2, 4, 5, 7, 9, 12, 14...",
	"0, 1, 3, 7, 11, 15, 23, 35, 43, 47...",
	"0, 2, 8, 14, 20, 38, 44, 62, 80, 98...",
	"1, 8, 8, 24, 8, 64, 24, 112, 8, 64...",
	"1, 1, 1, 2, 3, 4, 6, 9, 13, 19...",
	"4, 12, 18, 24, 30, 36, 42, 48, 54, 60...",
	"0, 1, 1, 2, 4, 9, 20, 48, 115, 286, 719...",
}

return function()
	return get(splashes[math.random(#splashes)])
end